source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass', '>= 2.1.1.0'
end

# The gem I'm testing
gem 'bootstrap_modal_rails', path: '/usr/local/gems/bootstrap_modal_rails'

gem 'unicorn', '>= 4.3.1'
gem 'mysql2', '>= 0.3.11'
gem 'haml', '>= 3.1.7'
gem 'simple_form', '>= 2.0.4'

group :development do
  gem 'haml-rails', '>= 0.3.5'
  gem 'hpricot', '>= 0.8.6'
  gem 'quiet_assets', '>= 1.0.1'
  gem 'ruby_parser', '>= 3.1.0'
end

group :development, :test do
  gem 'factory_girl_rails', '>= 4.1.0'
  gem 'rspec-rails', '>= 2.11.4'
  gem 'thin', '>= 1.5.0'
end

group :test do
  gem 'capybara', '>= 2.0.1'
  gem 'database_cleaner', '>= 0.9.1'
  gem 'email_spec', '>= 1.4.0'
end
